### ISSUE TITLE
Out of memory when running the example script on a single A40 GPU

### ISSUE THREAD

**Issue by AlonzoLeeeooo** [kyegomez/Med-PaLM#1]
Hi @kyegomez ,

Thanks for the amazing work! I was running the provided script  on a single A40 GPU but it ran into a OOM error. Is Med-PaLM has to be implemented on A100 GPU? Or is there any solution for this OOM problem? Thanks you in advance for any reply.

Best,

**Comment by kyegomez** [comment]
@AlonzoLeeeooo Hey thank you  for your appreciation😊 🙏 And, yes this happens alot, you 2 options:
- Lower hyperparameters, just cut them in half from where they are now
- Use smaller types like 16, 8bit

**Comment by AlonzoLeeeooo** [comment]
Thank you for the quick reply! I will try the provided solutions to see if it would work.

Best,
