### ISSUE TITLE
[WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.

### ISSUE THREAD

**Issue by dinesh1299** [kyegomez/Med-PaLM#13]
I'm getting this error while installing medpalm 

ERROR: Command errored out with exit status 1:
     command: 'c:\users\dinesh\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dinesh\\AppData\\Local\\Temp\\pip-install-083sifjl\\deepspeed\\setup.py'"'"'; __file__='"'"'C:\\Users\\dinesh\\AppData\\Local\\Temp\\pip-install-083sifjl\\deepspeed\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dinesh\AppData\Local\Temp\pip-pip-egg-info-he84ur2l'
         cwd: C:\Users\dinesh\AppData\Local\Temp\pip-install-083sifjl\deepspeed\
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dinesh\AppData\Local\Temp\pip-install-083sifjl\deepspeed\setup.py", line 147, in <module>
        assert torch_available, "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops."
    AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
    [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/Med-PaLM/issues/13">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/Med-PaLM/issues/13/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/Med-PaLM/issues/13/pledge.svg">
</picture>
</a>

**Comment by Thirumurugan-12** [comment]
did u find a solution for this problem ??

**Comment by kyegomez** [comment]
@Thirumurugan-12 just fixed this error, pls excuse me
