### ISSUE TITLE
Stupid Issues

### ISSUE THREAD

**Issue by White65534** [kyegomez/Med-PaLM#2]
in requirements.txt

deeepspeed ->  deepspeed 
Your misspelling.

in setup.py
install_requires=[
    "torch"
    "lion-pytorch",
    "numpy",
    "einops",
    "accelerate",
    "transformers",
    "SentencePiece",
    "datasets",
    "matplotlib",
    "deepspeed",
  ],

"torch" -> "torch", 
You forgot the comma.

**Comment by kyegomez** [comment]
@White65534 Thanks for your patience these are fixed now.
